a=input("Enter the first number: ")
b=input("Enter the second number: ")
a=int(a)
b=int(b)
Addition=(a+b)
Substraction=(a-b)
Multiplication=(a*b)
Division=(a/b)
print("Addition:",Addition)
print("Substraction:",Substraction)
print("Multiplication:",Multiplication)
print("Division:",Division)